CREATE DATABASE IF NOT EXISTS `BookData`;
USE `BookData`;

CREATE TABLE IF NOT EXISTS `Books` (
title VARCHAR(200) NOT NULL,
isbn13 BIGINT(13) NOT NULL PRIMARY KEY,
publisher VARCHAR(100) NOT NULL,
genre VARCHAR(20) NOT NULL,
royalties DECIMAL(5, 2),
cost Decimal (5,2),
INDEX `title` (`title` ASC) 
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `Authors` (
author_id INT(10) NOT NULL PRIMARY KEY,
author VARCHAR(50)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `Editors` (
editor_id INT(10) NOT NULL PRIMARY KEY,
editor VARCHAR(50)
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `BookEditors` (
isbn13 BIGINT(13) NOT NULL,
editor_id INT(10),
FOREIGN KEY (`isbn13`) REFERENCES `Books` (`isbn13`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION,
FOREIGN KEY (`editor_id`) REFERENCES `Editors` (`editor_id`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `BookAuthors` (
isbn13 BIGINT(13) NOT NULL,
author_id INT(10),
FOREIGN KEY (`isbn13`) REFERENCES `Books` (`isbn13`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION,
FOREIGN KEY (`author_id`) REFERENCES `Authors` (`author_id`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS `Orders`(
order_id INT(11) NOT NULL,
customer_name VARCHAR(55) NOT NULL,
isbn13 BIGINT(13) NOT NULL, 
copies INT(4) NOT NULL,
FOREIGN KEY (`isbn13`) REFERENCES `Books` (`isbn13`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

